### ISSUE TITLE
increase uploaded pic sizes 

### ISSUE THREAD

**Issue by TikoKershless** [heshamMassoud/Kershless-website#101]
Can we increase uploaded pics from 2mb to 3mb

**Comment by heshamMassoud** [comment]
Yes we can. Its only a risk, as I don't know how much space we have on the host.

**Comment by heshamMassoud** [comment]
so @TikoKershless ?

**Comment by TikoKershless** [comment]
Increase it and we will still leave the note of the 2mb in the reg page

**Comment by heshamMassoud** [comment]
@TikoKershless ok
