### ISSUE TITLE
Health status section in application form

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#16]
1. Description of problem if yes is checked for each question.
2. Allergy question should be added

![screen shot 2015-05-19 at 20 40 41](https://cloud.githubusercontent.com/assets/9512131/7710902/573a2e3a-fe67-11e4-8777-a18deb34c129.png)

**Comment by heshamMassoud** [comment]
@TikoKershless @MusliMinD :
I think there is no purpose for yes or no now. What about just having questions without yes or no. For example: 

## هل تعرضت لعمليات جراحية ؟ (ozkorha)

| Answer here |
| --- |

## هل تعاني من اي امراض مزمنة ( سكر - غده - كبد - قولون عصبي ) ؟ (ozkorha)

| Answer here |
| --- |

## هل تعاني من اي مشاكل في العمود الفقري او المفاصل ؟ (ozkorha)

| Answer here |
| --- |

## هل تتناول أدوية ؟ (ozkorha)

| Answer here |
| --- |

And simply if the user doesn't enter anything It means 'No', and if 'Yes' he will simply enter the details. There is no reason to have a checkbox for 'Yes' or 'No'  PLUS entering the description itself. It only affects the usability by forcing the user to make more clicks to complete the application.

What do you guys think?

**Comment by TikoKershless** [comment]
انا موافق ان احنا نشيل ( نعم و لا ) و نخط الخانة للإجابة علطول و لو ما كتبش حاجة يبقي ما عندوش

**Comment by heshamMassoud** [comment]
:+1:
