### ISSUE TITLE
Application form refinement

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#20]
- [x] Change application form according to screenshot : -
  - [x] Background color
  - [x] Subheader, picture height and weight height should have the same height and width as input textboxes.
  - [x] Section width
- [x] Logo Should redirect to homepage
- [x] @TikoKershless Please send new logo with dim: 190x98 px

![application_form_refined](https://cloud.githubusercontent.com/assets/9512131/7711641/19aba29c-fe6c-11e4-8b41-acbeade8715a.png)

**Comment by heshamMassoud** [comment]
@TikoKershless what is left here is for you to send me the logo with the new dim: 190x98 px. So I assigned you the issue.
I've done my subtasks in this issue. Check: http://www.kershless.com/register
BTW, I really like the new design of the application form ;) and I think the homepage should also have a consistent design with all the round edged green boxes.

**Comment by TikoKershless** [comment]
![kershless_190x98](https://cloud.githubusercontent.com/assets/12517255/8064212/03223168-0ee2-11e5-9731-eed4e2ab8638.png)

logo 190 px

**Comment by TikoKershless** [comment]
![kershless-logo-190px](https://cloud.githubusercontent.com/assets/12517255/8064378/fe0dbcb4-0ee2-11e5-9ca5-206c503fbd0e.png)

**Comment by heshamMassoud** [comment]
@TikoKershless

**Comment by TikoKershless** [comment]
![kershless-logo-190x122](https://cloud.githubusercontent.com/assets/12517255/8316053/36149c52-19fd-11e5-86d9-0f48b29bd2ae.png)
i think i did it 
check this non-pix-elated version ;)

**Comment by TikoKershless** [comment]
i think it stills blurry 
@heshamMassoud plz check this link its talking about how to show logos on Retina displays using CSS tricks 
http://graphicdesign.stackexchange.com/questions/45021/how-to-save-logo-for-web-from-illustrator-logo-looks-pixelated-after-uploading 

![untitled-1](https://cloud.githubusercontent.com/assets/12517255/8317489/8ebdbd94-1a06-11e5-8b9b-6789ff8a933c.jpg)

**Comment by heshamMassoud** [comment]
https://css-tricks.com/using-svg/

**Comment by heshamMassoud** [comment]
Dropbox: Tarek folder (SVG image and code)

**Comment by TikoKershless** [comment]
@heshamMassoud 
Adjusted the SVG logo with right fonts :)
downloaded from here :

https://www.dropbox.com/home/Kershless%20Website/tarek/Kershless%20Logo/SVG%20logo?preview=Kershless+logo+SVG1.svg

**Comment by heshamMassoud** [comment]
@TikoKershless what was the problem ? :smile:

**Comment by TikoKershless** [comment]
@heshamMassoud  
When you "save as" SVG file , choose " SVG Type : Convert to outline  
as in the attached screen shot :)
am happy that we did it finally :))))))
Good job bro
![image](https://cloud.githubusercontent.com/assets/12517255/8349140/28164e8a-1b23-11e5-97c6-0da6cc6c9752.png)

**Comment by heshamMassoud** [comment]
:+1:
