### ISSUE TITLE
Slider Indicators

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#22]
What is the situation with the slider indicators:-
- [ ] Do we need them?  
- [ ] If yes, where exactly? 

![screen shot 2015-05-19 at 23 02 22](https://cloud.githubusercontent.com/assets/9512131/7713937/4928d864-fe7b-11e4-96c2-2d3eb81f3e89.png)

**Comment by heshamMassoud** [comment]
@TikoKershless , @MusliMinD guys I will need your answer regarding this issue please.

**Comment by TikoKershless** [comment]
تحت الصور بتاعة ال slider

**Comment by heshamMassoud** [comment]
@TikoKershless I will move this issue to next week. Since the whole design of the homepage will be changed anyways.

**Comment by heshamMassoud** [comment]
@TikoKershless Do you still them want them under the picture or the same way as they are right now?

**Comment by TikoKershless** [comment]
Over the photos as it is now

**Comment by heshamMassoud** [comment]
ok (Y)

**Comment by heshamMassoud** [comment]
Should be centered
