### ISSUE TITLE
Application Success page

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#31]
![screen shot 2015-05-22 at 19 14 56](https://cloud.githubusercontent.com/assets/9512131/7775850/f2babad6-00b6-11e5-84e2-9b5a135ba8f3.png)

Will the design stay like this @TikoKershless @MusliMinD ?

**Comment by TikoKershless** [comment]
Will change it today abd send it to you @heshammassoud

**Comment by heshamMassoud** [comment]
@TikoKershless ??

**Comment by heshamMassoud** [comment]
1. White background
2. Logo will send it to me 
3. Kershless 2014 -> 2015
4. Logo redirects to homepage.
5. Text will be in dark blue as home page

**Comment by TikoKershless** [comment]
![409-logo](https://cloud.githubusercontent.com/assets/12517255/8267691/322011de-1774-11e5-94de-11254debb171.png)

**Comment by heshamMassoud** [comment]
![screen shot 2015-06-24 at 16 35 45](https://cloud.githubusercontent.com/assets/9512131/8332613/203759e6-1a8f-11e5-8f20-8de2bce36f8b.png)

**Comment by heshamMassoud** [comment]
![screen shot 2015-06-25 at 19 56 21](https://cloud.githubusercontent.com/assets/9512131/8391927/29f16fae-1cd7-11e5-8356-a07c5bfe3b9a.png)
