### ISSUE TITLE
color for text at the bottom 

### ISSUE THREAD

**Issue by TikoKershless** [heshamMassoud/Kershless-website#38]
Change color of text at the bottom under the button to dark grey

**Comment by heshamMassoud** [comment]
@TikoKershless Which button?

**Comment by TikoKershless** [comment]
" all rights reserved kershless.com 2015 " 
It is in white and after changing the background to white and diesnt appear

**Comment by heshamMassoud** [comment]
Ah ok! Nice! #eagleEyes :wink:
