### ISSUE TITLE
Do you know him?

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#46]
@TikoKershless @MusliMinD 
![14324876591432487683959](https://cloud.githubusercontent.com/assets/9512131/7789208/2a1fe30e-0259-11e5-9568-3a0e353be95b.jpg)

Because the picture was uploaded on the host today.. Just to make sure, if no stranger is messing around.

**Comment by TikoKershless** [comment]
Heheheeheh this is sherif hegazy, one of kershless team members , when i told them to check the registeration page today :)

**Comment by heshamMassoud** [comment]
@TikoKershless does he have accesss to the phpmyadmin page because apparently there is no record in the database, so he must have deleted it right?

**Comment by TikoKershless** [comment]
He only took a pic but didnt registered

**Comment by heshamMassoud** [comment]
ah ok :)
