### ISSUE TITLE
Upload profile picture image

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#54]
Should be 126x126 px

**Comment by heshamMassoud** [comment]
@TikoKershless ??

**Comment by TikoKershless** [comment]
![cam-icon1](https://cloud.githubusercontent.com/assets/12517255/8269779/694ede26-17c2-11e5-988b-c478a389c588.png)

![cam-icon2](https://cloud.githubusercontent.com/assets/12517255/8269780/71368314-17c2-11e5-91a9-cd037042cfc8.png)

**Comment by heshamMassoud** [comment]
@TikoKershless which one?

**Comment by TikoKershless** [comment]
1st one plz

**Comment by heshamMassoud** [comment]
@TikoKershless ok

**Comment by TikoKershless** [comment]
![cam-icon3](https://cloud.githubusercontent.com/assets/12517255/8317272/e5bf0942-1a04-11e5-9aec-222f5f4b3dca.png)
can u put this one with text under it  :
صورة شخصية

**Comment by heshamMassoud** [comment]
Please provide one with text in image @TikoKershless

**Comment by TikoKershless** [comment]
![cam-icons3](https://cloud.githubusercontent.com/assets/12517255/8336722/18ecaaea-1aaf-11e5-85ee-69b34b4846a3.png)

**Comment by TikoKershless** [comment]
![cam-icon4](https://cloud.githubusercontent.com/assets/12517255/8336988/d9d69e36-1ab0-11e5-8d81-054ce1b6b746.png)

**Comment by TikoKershless** [comment]
![cam-icon5](https://cloud.githubusercontent.com/assets/12517255/8337034/27d055e6-1ab1-11e5-8ab0-f28c1df36b01.png)

**Comment by TikoKershless** [comment]
use last one @heshamMassoud
