### ISSUE TITLE
Design contact us via e-mail form as a third section in the form

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#58]

**Comment by TikoKershless** [comment]
![contact form1](https://cloud.githubusercontent.com/assets/12517255/8267541/d786b476-176e-11e5-8cfa-3b0e8a351c5d.jpg)

**Comment by heshamMassoud** [comment]
'How can I help you' --> 'Kayf nosa3adek ?'
'Email' --> 'elbareed elelectroni' and change it in application to
'Tawasel ma3ana' should also be the same as the "Ma howa kershless section above" 
Remove the header 'elra2iseya'

**Comment by heshamMassoud** [comment]
Emails will be sent to : applications@kershless.com, unless you want another email

**Comment by heshamMassoud** [comment]
contact@kershless.com

**Comment by heshamMassoud** [comment]
Change to contact@kershless.com
