### ISSUE TITLE
الشروط و الأحكام page refinements

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#69]
1. Kershless in english should have spaces between arabic words
2. يحق لـ®Kershless بخأن ترفض أي نموذج اشتراك دون أن توضح السبب لذلك. أي قرار اتخذ بهذا الشأن سيكون نهائيا و ملزما ولا يخضع لأي اعتراض. Should be fixed "be2an"
3. Kershless 2014 -> 2015
4. 'hamza' character is different on phone than on web

**Comment by heshamMassoud** [comment]
All done except point 4

**Comment by heshamMassoud** [comment]
Font is not working: I need a new font with all these format files to be supported accross diferent browsers: 
.eot
.woff
.ttf
.svg

@TikoKershless now assigned to you.

**Comment by heshamMassoud** [comment]
http://www.sitepoint.com/how-to-use-cross-browser-web-fonts-part-1/

**Comment by TikoKershless** [comment]
Font Name :  Bahij_TheSansArabic-Light

i uploaded it on dropbox 
or you can downloaded it from here :
http://www.fonts2u.com/bahij-thesansarabic-semilight.font 
click on "Font Face" not " Download"
![image](https://cloud.githubusercontent.com/assets/12517255/8269164/da35774c-17a6-11e5-935c-4a99377e362d.png)
