### ISSUE TITLE
Add the Images to the slider with their texts

### ISSUE THREAD

**Issue by heshamMassoud** [heshamMassoud/Kershless-website#9]

**Comment by TikoKershless** [comment]
Slider photos uploaded to drop box with text and background color

![slider1](https://cloud.githubusercontent.com/assets/12517255/8269650/b1f14fd0-17bb-11e5-80cf-99e8cabe3546.jpg)
![slider2](https://cloud.githubusercontent.com/assets/12517255/8269652/b4f169c2-17bb-11e5-8546-401ff28ccbc0.jpg)
![slider3](https://cloud.githubusercontent.com/assets/12517255/8269653/b86ddfa4-17bb-11e5-99a6-b446e2e430fe.jpg)
![slider4](https://cloud.githubusercontent.com/assets/12517255/8269655/bc1e2866-17bb-11e5-8ffe-dcf4ab035d49.jpg)
![slider5](https://cloud.githubusercontent.com/assets/12517255/8269656/be61bbe2-17bb-11e5-99d4-3ae89542b566.jpg)
![slider6](https://cloud.githubusercontent.com/assets/12517255/8269657/c0c805e4-17bb-11e5-9292-44a51a4f2d2e.jpg)
![slider7](https://cloud.githubusercontent.com/assets/12517255/8269658/c33c030c-17bb-11e5-878c-c34df0f7e5d7.jpg)
![slider8](https://cloud.githubusercontent.com/assets/12517255/8269659/c6826f42-17bb-11e5-9906-4a62b7a75e62.jpg)

**Comment by heshamMassoud** [comment]
el sowar pixelated @TikoKershless

**Comment by TikoKershless** [comment]
![slider1](https://cloud.githubusercontent.com/assets/12517255/8297245/2fe3e03e-1964-11e5-984c-3f322afe9075.jpg)
![slider2](https://cloud.githubusercontent.com/assets/12517255/8297247/341a2f78-1964-11e5-84ea-5bc7a240f328.jpg)
![slider3](https://cloud.githubusercontent.com/assets/12517255/8297248/37b89d68-1964-11e5-9e95-34599fcd716b.jpg)
![slider4](https://cloud.githubusercontent.com/assets/12517255/8297251/3a367b5a-1964-11e5-9d0b-3e9e107e3efe.jpg)
![slider5](https://cloud.githubusercontent.com/assets/12517255/8297254/3c1d3e7c-1964-11e5-8a67-f6c30c08f1ee.jpg)
![slider6](https://cloud.githubusercontent.com/assets/12517255/8297255/3df81500-1964-11e5-8775-0771b445211a.jpg)
![slider7](https://cloud.githubusercontent.com/assets/12517255/8297256/400129cc-1964-11e5-9d38-de8f5ff20c47.jpg)
![slider8](https://cloud.githubusercontent.com/assets/12517255/8297257/423827ae-1964-11e5-821f-b1541690eb3e.jpg)

**Comment by TikoKershless** [comment]
![slider1](https://cloud.githubusercontent.com/assets/12517255/8353506/65c6b462-1b47-11e5-8c92-446bed919980.jpg)
![slider2](https://cloud.githubusercontent.com/assets/12517255/8353507/65d02ed4-1b47-11e5-88ff-63204fb6a26d.jpg)
![slider3](https://cloud.githubusercontent.com/assets/12517255/8353508/65d1041c-1b47-11e5-95d1-2a448ba845a6.jpg)
![slider4](https://cloud.githubusercontent.com/assets/12517255/8353509/65d52d12-1b47-11e5-99f5-f2e0b042c1b1.jpg)
![slider5](https://cloud.githubusercontent.com/assets/12517255/8353513/6609e07a-1b47-11e5-9f32-daee79c5c866.jpg)
![slider6](https://cloud.githubusercontent.com/assets/12517255/8353510/65eb4908-1b47-11e5-800a-4d7bbc957161.jpg)
![slider7](https://cloud.githubusercontent.com/assets/12517255/8353511/65f99878-1b47-11e5-917b-380ed4960d54.jpg)
![slider8](https://cloud.githubusercontent.com/assets/12517255/8353512/6604590c-1b47-11e5-8e10-91d9a4800811.jpg)
