### ISSUE TITLE
Adjustments in Home page on Mobile

### ISSUE THREAD

**Issue by TikoKershless** [heshamMassoud/Kershless-website#97]
![photo jun 28 4 43 18 pm](https://cloud.githubusercontent.com/assets/12517255/8396615/8502b788-1db6-11e5-8abc-33326d1d78ea.jpg)
1. The upper button on the left ( remove the rectangular frame or make it white ) 
2. make kershless logo bigger 
3. " what is kershless ? " appears part of it  on Samsung mobile on the main screen , can we make the main screen without it 
   @heshamMassoud

**Comment by heshamMassoud** [comment]
@TikoKershless What is the screen size of this Samsung mobile?

**Comment by TikoKershless** [comment]
Samsung S3

**Comment by heshamMassoud** [comment]
@TikoKershless S3 or S5 ?

**Comment by TikoKershless** [comment]
S5
